### PR TITLE
Update settings.gradle

### PR DESCRIPTION
**Pull request by errysuprayogi**

### CODE REVIEW

**Comment by errysuprayogi** [comment]
test

**Comment by professorflux** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/errysuprayogi/TinkerSampleApp/blob/2de04e17a0bd8301de2c75631573fda4dbea7e44/app/src/main/java/com/tokopedia/sample/utils/ScreenUtils.kt#L27">app/src/main/java/com/tokopedia/sample/utils/ScreenUtils.kt#L27</a> - Exceeded max line length (100)</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/errysuprayogi/TinkerSampleApp/blob/2de04e17a0bd8301de2c75631573fda4dbea7e44/app/src/main/java/com/tokopedia/sample/utils/UserPrefs.kt#L3">app/src/main/java/com/tokopedia/sample/utils/UserPrefs.kt#L3</a> - Unused import</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          2 Messages
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><code>settings.gradle</code> was modified</td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Thank you for your work @errysuprayogi 🎉 You might find a few suggestions from me below 😉</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by errysuprayogi — COMMENTED** [review]
test

**Review by errysuprayogi — COMMENTED** [review]
adsdsd

**Review by professorflux — CHANGES_REQUESTED** [review]
request change

**Review by professorflux — APPROVED** [review]
approved

**Pull request merged**
